import "@styles/globals.css";
import { Inter } from "next/font/google";
import HeaderOne from "@components/layouts/headers/headerOne";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wrocław",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={inter.className}>
        <main>
        <HeaderOne/>
            {children}
        </main>
      </body>
    </html>
  );
}
